introduce: |
  我是哥伦比亚大学企业风险管理硕士，专注于AI与金融领域的融合应用，拥有扎实的数据分析与建模基础。具备从零构建NLP模型、开发自动化项目管理系统的实践经验，曾主导欺诈检测模型优化与GPT类项目落地，技术与业务理解兼备。期待在贵公司发挥技术专长与创新能力，共同推动金融科技的发展。

prompt: |
  请根据以下“我的简历内容”与“职位描述”，生成一段适用于求职平台打招呼的中文自我介绍，要求语气自然真诚，突出技术能力与岗位契合度，控制在200字以内，避免出现套话与无关内容：

  【我的简历内容】
  {resume}

  【职位描述】
  {jd}
