boss:
  sayHi: []  # 使用 AI 动态生成
  keywords: [ "AI", "AIGC", "数据分析", "算法", "风控", "金融科技", "推荐系统", "大模型" ]
  industry: [10101, 10001]
  cityCode: [101280600, 101020100, 101010100]  # 香港: 101280600, 深圳: 101020100, 上海: 101010100
  experience: [ "应届毕业生" ]
  jobType: "全职"
  salary: "8K以上"  # 实际项目中不识别文字，此处供说明
  degree: [ "本科", "硕士" ]
  scale: [ "不限" ]  # 公司规模不限制
  stage: [ "不限" ]
  expectedSalary: [ 8 ]  # 期望薪资 8K+
  filterDeadHR: true
  enableAI: true
  fakeUserAction: false

job51:
  jobArea: [ "香港", "深圳", "上海" ]
  keywords: [ "数据分析", "AI", "AIGC", "算法", "风控", "金融科技", "推荐系统", "大模型" ]
  salary: [ "0.8-1万", "1-1.5万", "1.5-2万", "2-3万", "3-4万", "4-5万", "5万以上" ]

lagou:
  keywords: [ "AI工程师", "数据分析", "风控", "AIGC", "算法", "推荐系统" ]
  cityCode: "深圳"  # 香港暂未收录，拉勾网主要是内地城市
  salary: "8k以上"
  scale: [ "不限" ]
  gj: "在校/应届,3年及以下"

liepin:
  cityCode: "深圳"  # 香港暂不支持，建议优先深圳
  keywords: [ "数据分析", "AI", "风控", "算法", "大模型" ]
  containsJobName: "AI,风控,数据,分析"
  excludeCompany: "外包,中软,中科软,海隆,博彦,软通,IBM,银行,政府"
  excludeJobName: "外包,政府,银行,C,.NET,安卓"

zhilian:
  cityCode: "深圳"
  salary: "8000,35000"
  keywords: [ "数据分析", "金融科技", "AI工程师", "AIGC", "算法", "推荐系统", "风控" ]
